### ISSUE TITLE
Add Uniprot localisation data

### ISSUE THREAD

**Issue by Nusob888** [pachterlab/gget#45]
Many thanks for this brilliant tool. I was wondering if it would be possible to add the "subcellular localisation" segment of the uniprot ID to the tools output? 

This would be immensely helpful in terms of filtering for sub cellular location. 

Many thanks and apologies if it does this already, but I couldn't identify this data in the output

**Comment by lauraluebbert** [comment]
Hi, thank you very much for the suggestion! I implemented the subcellular localisation info from UniProt as part of the `gget info` output. It will be part of the next gget release.

You can already install and use the new version by installing gget from source with `pip install git+https://github.com/pachterlab/gget`. If you then run gget info on an Ensembl ID, e.g. `gget info ENSG00000130234` (or Python: `gget.info("ENSG00000130234")`), you should get the new "subcellular_localisation" output. Would you mind giving it a try? I would love to hear if this is what you were going for and if you have any further suggestions.

**Comment by Nusob888** [comment]
Hi, 

Sorry it took so long. That is brilliant thank you. 
I don't want to cause more work, but is there any thoughts in future of being able to gget proteins from a reference that meet certain criteria?

e.g. get ref homosapiens, but only genes that encode cell membrane proteins? or another info parameter

No worries if not

Thanks so much for adding the additional info

**Comment by lauraluebbert** [comment]
Wonderful, I'm glad it works for you! I just released gget version 0.3.12, which includes a bunch of improvements, as well as your proposed enhancement to include subcellular localization data. I'll close this issue for now, since this solves the initial request.

For the second request, do you know of an existing API that can fetch parts of a reference genome based on certain criteria? If so, I could integrate it into gget.
