### ISSUE TITLE
Option to BLAST one protein sequence against another

### ISSUE THREAD

**Issue by hoangthienan95** [pachterlab/gget#5]
Thank you for the very cool and important package! This will save me hours and hours of computational work

I was wondering if you can add an option to BLAST two protein sequences against each other and get their e-value etc. I have a list of proteins that I want to compare to each other. If you'd prefer to point me to how I can make this feature and do a pull request, I'm more than happy to do so too!

**Comment by lauraluebbert** [comment]
Currently, gget blast runs the BLAST on the NCBI BLAST server. This, unfortunately, limits it to the databases available on the server (if anybody has any ideas on how to circumvent this, I would love to hear them).  
However, NCBI has its own command-line program called [BLAST+](https://www.ncbi.nlm.nih.gov/books/NBK279670/), which runs a BLAST locally and allows the user to align to custom databases. When building gget blast, I decided to use the server instead of BLAST+ because it does not require the user to download a database. However, for your case, BLAST+ might be the better option. I would love to hear about your experience with it if you give it a try.  
One option for gget would be to build a "gget blast+" module that locally compiles the BLAST+ binary (similarly to what gget muscle does for Muscle v5). The question would be how to facilitate the database download/building of a custom database. Feel free to give it a try, I would be happy to help!

**Comment by lauraluebbert** [comment]
Hi, it took a while but this feature will be available in gget version 0.28.0 through `gget diamond`. Thank you again for your suggestion! :)

**Comment by hoangthienan95** [comment]
Thanks so much for following up! This is awesome!!
