### ISSUE TITLE
potential issue with UniProt connection

### ISSUE THREAD

**Issue by keoughkath** [pachterlab/gget#6]
Hello,

Thanks for the great package. I think there may be intermittent issues with the UniProt connection, I received this error today:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/13281889/170573420-43480e79-8dc1-48da-b0b0-408cda357a9d.png">

But as you can see, there is a UniProt entry for this gene: https://www.uniprot.org/uniprot/Q8NBP7

Oddly, grabbing amino acid sequences worked fine for me yesterday. I appreciate any tips!

**Comment by lauraluebbert** [comment]
I cannot solve the issue on my end, which leads me to believe that this is a problem with the UniProt REST API. I contacted their team and will keep you updated. Thank you for bringing this issue to my attention!

**Comment by keoughkath** [comment]
Great, thank you!

**Comment by lauraluebbert** [comment]
On May 25th, UniProt released [version 2022_02](https://www.uniprot.org/news/2022/05/25/release). They added version number identifiers for Ensembl IDs as part of this release. This would not be a problem, except currently, the API does not seem to accept any Ensembl IDs, neither with nor without a version number. It looks like they are still working on updating the API, but it will hopefully happen soon.

**Comment by lauraluebbert** [comment]
On May 25th, UniProt released [version 2022_02](https://www.uniprot.org/news/2022/05/25/release). This version introduced a requirement for Ensembl ID version numbers. However, this requirement is not true (yet?) for all IDs. As far as I can tell, it seems to be true for most homo sapiens IDs. I adjusted gget accordingly. Please upgrade to the latest gget version, and your query should work again.  

Please note that due to the ongoing changes to the UniProt API, there might be more issues in the coming days. Please let me know if you notice anything else. In the meantime, I am working with the UniProt team to get to a consistent solution.
